version: '3'
services:
    web:
        build: .
        command: flask run --host=0.0.0.0
        environment:
          - FLASK_APP=api.py
          - FLASK_DEBUG=1
        volumes:
            - .:/code
        ports:
            -  "5000:5000"
